vault_hcloud_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
vault_woodpecker_github_client: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
vault_woodpecker_github_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
vault_woodpecker_agent_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
vault_woodpecker_agent1_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
vault_weblate_email_host: mail.example.com
vault_weblate_email_username: mail@example.com
vault_weblate_email_password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
vault_weblate_postgres_password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
vault_weblate_admin_email: mail@example.com
vault_woodpecker_api_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

